name: OverBlock
version: '${project.version}'
main: me.chaoticwagon.overblock.Main
api-version: 1.17
authors: [ ChaoticWagon, Skrate67 ]
description: pew pew boom
commands:
  guns:
    description: "Opens guns GUI"
    usage: /guns
    aliases: [ gun ]
